name: Percy Tests

on:
  schedule:
    - cron: '0 13 * * 1,3,5'  # 10 AM GMT-3 → 13:00 UTC
  workflow_dispatch:  # Permite ejecución manual

jobs:
  percy-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Crear cypress.env.json
        run: echo '${{ secrets.CYPRESS_ENV }}' > cypress.env.json

      - name: Run Percy Tests
        run: npx percy exec -- cypress run --browser chrome
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
